/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/circuitMesh.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const CircuitMesh = ({ color, position = [0, 0, -2.5] }) => {
  const { nodes, materials } = useGLTF('/models/circuitMesh.gltf')
  return (
    <group
      // {...props}
      dispose={null}
      scale={12}
      position={position}
      // position={[0, 0, 0]}
    >
      <mesh geometry={nodes.Plane.geometry}>
        <meshBasicMaterial
          wireframe
          // color={'#556666'}
          color={color}
        />
      </mesh>
    </group>
  )
}

export default CircuitMesh

useGLTF.preload('/models/circuitMesh.gltf')
